### ISSUE TITLE
An error occurred while sending the song when finishing downloading apple music

### ISSUE THREAD

**Issue by lsyyktv** [bdim404/music-download-telegram-bot#4]
![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/ae8feac6-2f9f-46e1-bef4-9ce7af904bcc)

When finishing downloading apple music，an error occurred while sending the song，while spotify music is normal

**Comment by bdim404** [comment]
![Snipaste_2024-04-14_13-25-22](https://github.com/bdim404/music-download-telegram-bot/assets/102711645/7c708082-04af-4ec1-a1f2-3bfc1d3caeba)
I have no problem downloading and sending here, it should be a network problem, I get 5 retries for failed sends here. If they all fail, please check your internet link situation.

**Comment by lsyyktv** [comment]
> ![Snipaste_2024-04-14_13-25-22](https://private-user-images.githubusercontent.com/102711645/322249126-7c708082-04af-4ec1-a1f2-3bfc1d3caeba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzI2ODcsIm5iZiI6MTcxMzA3MjM4NywicGF0aCI6Ii8xMDI3MTE2NDUvMzIyMjQ5MTI2LTdjNzA4MDgyLTA0YWYtNGVjMS1hMWYyLTNiZmMxZDNjYWViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwNTI2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGY2NGUyYzIyZTNjZTQ5MGQ0ZGYzMDI5ZTJkY2VkNDg1M2RiNmJiZGUyY2E4OGYwZWFiYTFiMGYzMmE1YjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y1iYXxudHhhq1Otp9bPyMhO2skj1bJgON-RxKN8Eodo) I have no problem downloading and sending here, it should be a network problem, I get 5 retries for failed sends here. If they all fail, please check your internet link situation.

I have changed several oracle vps（KR，SG，US）to test，the internet should have no problem as other bots are running normally

**Comment by lsyyktv** [comment]
> ![Snipaste_2024-04-14_13-25-22](https://private-user-images.githubusercontent.com/102711645/322249126-7c708082-04af-4ec1-a1f2-3bfc1d3caeba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzI2ODcsIm5iZiI6MTcxMzA3MjM4NywicGF0aCI6Ii8xMDI3MTE2NDUvMzIyMjQ5MTI2LTdjNzA4MDgyLTA0YWYtNGVjMS1hMWYyLTNiZmMxZDNjYWViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwNTI2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGY2NGUyYzIyZTNjZTQ5MGQ0ZGYzMDI5ZTJkY2VkNDg1M2RiNmJiZGUyY2E4OGYwZWFiYTFiMGYzMmE1YjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y1iYXxudHhhq1Otp9bPyMhO2skj1bJgON-RxKN8Eodo) I have no problem downloading and sending here, it should be a network problem, I get 5 retries for failed sends here. If they all fail, please check your internet link situation.

![N@U(}{03G0 OJX~WI90 E3S](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/e1674173-818d-48b4-947b-ea8638513c9a)
Maybe there is something wrong with this part？I have install ffmpeg correctly

**Comment by bdim404** [comment]
I'm testing this on macOS, I'll test it on Debian later, it seems to be problematic.

**Comment by lsyyktv** [comment]
> I'm testing this on macOS, I'll test it on Debian later, it seems to be problematic.

似乎我們可以用中文交流，哈哈
我找到問題了，是debian apt 庫裡面自帶的ffmpeg版本過低導致的，我重新手動安裝最新版後正常了
另外，還想請教一下你，現在的情況是只能私聊bot發送鏈接進行下載，如果我把bot添加到群組或者頻道後並設置為管理員，發送鏈接，bot不會有任何反應，並且我在.env裡面只找到頻道ID的設置，也設置了頻道ID

**Comment by bdim404** [comment]
> > I'm testing this on macOS, I'll test it on Debian later, it seems to be problematic.
> 
> 似乎我們可以用中文交流，哈哈 我找到問題了，是debian apt 庫裡面自帶的ffmpeg版本過低導致的，我重新手動安裝最新版後正常了 另外，還想請教一下你，現在的情況是只能私聊bot發送鏈接進行下載，如果我把bot添加到群組或者頻道後並設置為管理員，發送鏈接，bot不會有任何反應，並且我在.env裡面只找到頻道ID的設置，也設置了頻道ID

可以，我这里在群组中下载为了避免打扰是使用了 /download 这个命令，使用 /download 回复包含音乐的信息，就可以下载。

**Comment by lsyyktv** [comment]
> > > I'm testing this on macOS, I'll test it on Debian later, it seems to be problematic.
> > 
> > 
> > 似乎我們可以用中文交流，哈哈 我找到問題了，是debian apt 庫裡面自帶的ffmpeg版本過低導致的，我重新手動安裝最新版後正常了 另外，還想請教一下你，現在的情況是只能私聊bot發送鏈接進行下載，如果我把bot添加到群組或者頻道後並設置為管理員，發送鏈接，bot不會有任何反應，並且我在.env裡面只找到頻道ID的設置，也設置了頻道ID
> 
> 可以，我这里在群组中下载为了避免打扰是使用了 /download 这个命令，使用 /download 回复包含音乐的信息，就可以下载。你可以通过 /help 来获取使用方式的信息。

謝謝解答，可是當我使用了/download命令後，bot會有如圖提示，而不是開始下載
![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/74718363-81ca-4f93-abb6-0eeb6d9227b0)

**Comment by lsyyktv** [comment]
> > > I'm testing this on macOS, I'll test it on Debian later, it seems to be problematic.
> > 
> > 
> > 似乎我們可以用中文交流，哈哈 我找到問題了，是debian apt 庫裡面自帶的ffmpeg版本過低導致的，我重新手動安裝最新版後正常了 另外，還想請教一下你，現在的情況是只能私聊bot發送鏈接進行下載，如果我把bot添加到群組或者頻道後並設置為管理員，發送鏈接，bot不會有任何反應，並且我在.env裡面只找到頻道ID的設置，也設置了頻道ID
> 
> 可以，我这里在群组中下载为了避免打扰是使用了 /download 这个命令，使用 /download 回复包含音乐的信息，就可以下载。你可以通过 /help 来获取使用方式的信息。
謝謝解答，可是當我使用了/download命令後，機器人會有如圖所示的回復
![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/03bcf6c0-4fe6-4cda-aaac-3fd603537083)

**Comment by bdim404** [comment]
> 使用 /download 回复包含音乐的信息，就可以下载。

^
“回复”

**Comment by lsyyktv** [comment]
> > 使用 /download 回复包含音乐链接的信息，就可以下载。
> 
> ^ “回复”

哦，明白了，原來是要先發命令，再把鏈接回復給機器人。因為我其他bot都是直接命令+URL就能解析，犯了習慣性的錯誤了。

不好意思，最後一個問題需要請教，如果“ALLOWED_TELEGRAM_USER_IDS”這一項設置為*，啟動腳本會報錯：
![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/c035b6a6-dfd0-4d98-b7dc-9b38e91de982)

![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/ff721205-3248-45b9-90db-743aa3db6ad1)

**Comment by lsyyktv** [comment]
> > 使用 /download 回复包含音乐链接的信息，就可以下载。
> 
> ^ “回复”

我應該是有理解到你的意思，可是還是不行，當我發送/download命令激活機器人，然後再此回復它，還是沒有反應
![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/88e6dc57-3d2b-428e-833e-bd46108dbe13)

這裡會先顯示群Group送了一個命令，然後就會卡在user sent a message不動了
![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/1e86713a-8ece-4a5c-bb20-e09533b8a57e)

**Comment by bdim404** [comment]
> > > 使用 /download 回复包含音乐链接的信息，就可以下载。
> 
> > 
> 
> > ^ “回复”
> 
> 
> 
> 我應該是有理解到你的意思，可是還是不行，當我發送/download命令激活機器人，然後再此回復它，還是沒有反應
> 
> ![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/88e6dc57-3d2b-428e-833e-bd46108dbe13)
> 
> 
> 
> 這裡會先顯示群Group送了一個命令，然後就會卡在user sent a message不動了
> 
> ![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/19a91748-e63a-4011-b96f-0901abe4b56f)
> 
> 
> 
> 

![image](https://github.com/bdim404/music-download-telegram-bot/assets/102711645/08f57a94-e002-4772-840f-432db49ae326)

**Comment by lsyyktv** [comment]
> > > > 使用 /download 回复包含音乐链接的信息，就可以下载。
> > 
> > 
> > > 
> > 
> > 
> > > ^ “回复”
> > 
> > 
> > 我應該是有理解到你的意思，可是還是不行，當我發送/download命令激活機器人，然後再此回復它，還是沒有反應
> > ![image](https://private-user-images.githubusercontent.com/39065858/322258600-88e6dc57-3d2b-428e-833e-bd46108dbe13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwODU1NjUsIm5iZiI6MTcxMzA4NTI2NSwicGF0aCI6Ii8zOTA2NTg1OC8zMjIyNTg2MDAtODhlNmRjNTctM2QyYi00MjhlLTgzM2UtYmQ0NjEwOGRiZTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDA5MDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmM2NiOGI4MGQ4ZTIxNDVjNDdiZmRmYzc0YTViYjYyZTdmY2JlYzIxZDZjNDcxOTQ3ZjNlYmNhYWEyMDYxMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E7ee89AgPe2S59QEkLIQexqLA1T1XEx7T35i1W6Jh9Y)
> > 這裡會先顯示群Group送了一個命令，然後就會卡在user sent a message不動了
> > ![image](https://private-user-images.githubusercontent.com/39065858/322258811-19a91748-e63a-4011-b96f-0901abe4b56f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwODU1NjUsIm5iZiI6MTcxMzA4NTI2NSwicGF0aCI6Ii8zOTA2NTg1OC8zMjIyNTg4MTEtMTlhOTE3NDgtZTYzYS00MDExLWI5NmYtMDkwMWFiZTRiNTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDA5MDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTFmM2I2NzAxN2U2ZDMyZWQxNmQwMzI2ZmVhNzRiMzI4ZWZhZDI0NGY1ODAyNmVjZGU3ZmNiNjUzNmFiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TIx9To9uqSkuKuVyraMnEzz4WMnTFsfEqF8sCwSZZRM)
> 
> ![image](https://private-user-images.githubusercontent.com/102711645/322259658-08f57a94-e002-4772-840f-432db49ae326.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwODU1NjUsIm5iZiI6MTcxMzA4NTI2NSwicGF0aCI6Ii8xMDI3MTE2NDUvMzIyMjU5NjU4LTA4ZjU3YTk0LWUwMDItNDc3Mi04NDBmLTQzMmRiNDlhZTMyNi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMDkwMTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJmNjcxZWNkYmY1ODUxY2VjMGY3ODZiMzNjMzVhOTMyMWYyODBlMzNiOTU3MDE5MmJmNTI5Nzg0ZThkM2IzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZDa7bZQVjNBN6easEOTa5QIDjghmGSvRvvxg8OUaaZQ)

原來是這樣操作啊，我這是犯了習慣主義的錯誤了，因為我其他BOT都是命令+URL直接解析，謝謝謝謝！

不好意思，最後一個問題需要請教，如果“ALLOWED_TELEGRAM_USER_IDS”這一項設置為*，啟動腳本會報錯：

![}W%_7UFW7F8UF)$I5U0Q( C](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/317fe242-b99b-4e4d-a59c-16bdf00e2b52)
![CHS FY7_~K9A1K J$GFCDAD](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/270612e8-73e1-452b-ab0c-4778d4b88db8)

**Comment by bdim404** [comment]
这里应该是我的代码逻辑的问题。

**Comment by lsyyktv** [comment]
> > 不好意思，最後一個問題需要請教，如果“ALLOWED_TELEGRAM_USER_IDS”這一項設置為*，啟動腳本會報錯：
> 
> 在新的commit中我已经修复了这个问题，[11dd1f4](https://github.com/bdim404/music-download-telegram-bot/commit/11dd1f4ded561f1736cca0cafd0ea0833c6e8690) 你可以通过 git pull 来获取更新。 有什么新的问题可以继续留言，如果觉得好用欢迎给我项目 Star ,非常感谢。后续我会继续更新版本。

已经更新，问题解决了。感谢！
最近Apple Music ALAC&Dolby Atoms 也能解密了，期待大佬的bot早日支持！
