### ISSUE TITLE
请问带E标的曲目是不是无法下载？

### ISSUE THREAD

**Issue by lsyyktv** [bdim404/music-download-telegram-bot#5]
下载了好几张专辑，但是只要是带E标的曲目就无法下载

**Comment by bdim404** [comment]
我这里没有问题，例如 https://music.apple.com/us/album/the-tortured-poets-department/1736268193?l=zh-Hans-CN
![图片](https://github.com/bdim404/music-download-telegram-bot/assets/102711645/0757ad8e-07ef-426e-832b-c26d4da7bf03)
我这里完全可以下载。
![图片](https://github.com/bdim404/music-download-telegram-bot/assets/102711645/fb898275-ad61-4931-ae5d-0ad7de193d7f)
![图片](https://github.com/bdim404/music-download-telegram-bot/assets/102711645/efdc5323-1166-4f90-8598-5770a99faf10)

**Comment by lsyyktv** [comment]
> 我这里没有问题，例如 https://music.apple.com/us/album/the-tortured-poets-department/1736268193?l=zh-Hans-CN ![图片](https://private-user-images.githubusercontent.com/102711645/323963923-0757ad8e-07ef-426e-832b-c26d4da7bf03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzE4MTYsIm5iZiI6MTcxMzUzMTUxNiwicGF0aCI6Ii8xMDI3MTE2NDUvMzIzOTYzOTIzLTA3NTdhZDhlLTA3ZWYtNDI2ZS04MzJiLWMyNmQ0ZGE3YmYwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxMjU4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzc3ZmFiOTM5ZjNmNTdiMTBjZmVkNjU1ZjExZjFmMmRlNWU3NTdjZjNiNjdlYTdjOTcyMjE2NGE0ZTI3MDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uHJBcORWTq6Qu7grnomryrbQsGpr9sjJH5Bh3vEr7As) 我这里完全可以下载。 ![图片](https://private-user-images.githubusercontent.com/102711645/323964297-fb898275-ad61-4931-ae5d-0ad7de193d7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzE4MTYsIm5iZiI6MTcxMzUzMTUxNiwicGF0aCI6Ii8xMDI3MTE2NDUvMzIzOTY0Mjk3LWZiODk4Mjc1LWFkNjEtNDkzMS1hZTVkLTBhZDdkZTE5M2Q3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxMjU4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjBlYjcxZTYyZWMyM2IzMzI2YTdkZWJiYTdlMGM1ZWU5MjkwOTUyNjdiOGI3ZmM5NmE2OTdkMWIxMzQ0MTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IeXSKd7OJv1lcIZLwYTUANIEWWWtKxAOg5pM-nP_dhU) ![图片](https://private-user-images.githubusercontent.com/102711645/323964358-efdc5323-1166-4f90-8598-5770a99faf10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzE4MTYsIm5iZiI6MTcxMzUzMTUxNiwicGF0aCI6Ii8xMDI3MTE2NDUvMzIzOTY0MzU4LWVmZGM1MzIzLTExNjYtNGY5MC04NTk4LTU3NzBhOTlmYWYxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxMjU4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGY5Y2QwM2RkNDcxMWI0ZGE3NTY2YjY2OTMyZWI0ZGE4OWI0MDZkMDgwMGVkZTI1NjU1OGYwNTE5YTQ3NTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c8dKl2wiBlNu-N-FppOZV1cBclRtf5qIbbVl-YnUTHs)

奇了怪了，这张我也只能下载不带E标的9首
![image](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/8d0049ee-b43c-4bd0-89b8-4e4c9d4b371a)

**Comment by lsyyktv** [comment]
遇到E标的歌曲会报这个错误
![EH MF3}%K8KC2HT0U@_Q% 4](https://github.com/bdim404/music-download-telegram-bot/assets/39065858/ae80ce36-c4ad-43f4-82b1-ee664c0c33d1)

**Comment by bdim404** [comment]
Can't reproduce.

**Comment by lsyyktv** [comment]
> Can't reproduce.

已经解决，谢谢！
